#!/bin/bash
set -ex

# Config
# Set default answers to the questions that microstack.init asks.
# TODO: put this in a nice yaml format, and parse it.
snapctl set \
        questions.ip-forwarding=true \
        questions.dns=1.1.1.1 \
        questions.ext-gateway=10.20.20.1 \
        questions.ext-cidr=10.20.20.1/24 \
        questions.os-password=keystone \
        questions.rabbit-mq=true \
        questions.database-setup=true \
        questions.nova-setup=true \
        questions.neutron-setup=true \
        questions.glance-setup=true \
        questions.key-pair="id_microstack" \
        questions.security-rules=true \
        questions.post-setup=true \

# MySQL snapshot for speedy install
# snapshot is a mysql data dir with
# rocky keystone,nova,glance,neutron dbs.
mkdir -p ${SNAP_COMMON}/lib

# Install conf.d configuration from snap for db etc
echo "Installing configuration for OpenStack Services"
for project in neutron nova keystone glance; do
    mkdir -p ${SNAP_COMMON}/etc/${project}/${project}.conf.d
    cp -r ${SNAP}/etc/${project}/${project}.conf.d/* ${SNAP_COMMON}/etc/${project}/${project}.conf.d || true # Skip conf files that have been moved into templates
done
# Make a place for our horizon config overrides to live
mkdir -p ${SNAP_COMMON}/etc/horizon/local_settings.d

snap-openstack setup  # Sets up templates for the first time.
